/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class AdminFunciones extends javax.swing.JFrame {

    public AdminFunciones() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jCheckBox5 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jCheckBox5.setText("jCheckBox5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Color:");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Adelantar:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Retrasar:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Volver a lanzar el dado:");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel5.setText("Funciones");

        buttonGroup1.add(jCheckBox1);
        jCheckBox1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jCheckBox1.setText("Verde");

        buttonGroup1.add(jCheckBox2);
        jCheckBox2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jCheckBox2.setText("Rojo");

        buttonGroup1.add(jCheckBox3);
        jCheckBox3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jCheckBox3.setText("Azul");

        buttonGroup1.add(jCheckBox4);
        jCheckBox4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jCheckBox4.setText("Amarillo");

        jTextFieldAdelantar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextFieldAdelantar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAdelantarActionPerformed(evt);
            }
        });

        jTextFieldRetrasar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jTextFieldDado.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jButton1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldAdelantar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(25, 25, 25)
                        .addComponent(jTextFieldRetrasar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(10, 10, 10)
                        .addComponent(jTextFieldDado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox1)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox2)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox3)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox4)))
                .addGap(0, 182, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(165, 165, 165)
                                .addComponent(jButton2))
                            .addComponent(jButton1))
                        .addGap(196, 196, 196))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(243, 243, 243))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel1))
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox4))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldAdelantar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldRetrasar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldDado, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Login.menuAdmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (buttonGroup1.isSelected(null) || jTextFieldAdelantar.getText().isEmpty() | jTextFieldRetrasar.getText().isEmpty() | jTextFieldDado.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "No deje espacios sin rellenar");
        } else {
            int Adelantar = Integer.parseInt(jTextFieldAdelantar.getText());
            int Retrasar = Integer.parseInt(jTextFieldRetrasar.getText());
            int LanzarDado = Integer.parseInt(jTextFieldDado.getText());

            if (Adelantar != 0 && Retrasar == 0 && LanzarDado == 0) {
                if (jCheckBox1.isSelected()) {
                    String Color = jCheckBox1.getText();
                    if (Login.metodos.crearFunciones(Color, Adelantar, Retrasar, LanzarDado) == true) {
                        JOptionPane.showMessageDialog(null, "Funcion creada");
                        Login.menuAdmin.setVisible(true);
                        this.dispose();
                        jTextFieldAdelantar.setText(null);
                        jTextFieldRetrasar.setText(null);
                        jTextFieldDado.setText(null);
                    }
                }
                if (jCheckBox2.isSelected()) {
                    String Color = jCheckBox2.getText();

                    if (Login.metodos.crearFunciones(Color, Adelantar, Retrasar, LanzarDado) == true) {
                        JOptionPane.showMessageDialog(null, "Funcion creada");
                        Login.menuAdmin.setVisible(true);
                        this.dispose();
                        jTextFieldAdelantar.setText(null);
                        jTextFieldRetrasar.setText(null);
                        jTextFieldDado.setText(null);
                    }
                }
                if (jCheckBox3.isSelected()) {
                    String Color = jCheckBox3.getText();

                    if (Login.metodos.crearFunciones(Color, Adelantar, Retrasar, LanzarDado) == true) {
                        JOptionPane.showMessageDialog(null, "Funcion creada");
                        Login.menuAdmin.setVisible(true);
                        this.dispose();
                        jTextFieldAdelantar.setText(null);
                        jTextFieldRetrasar.setText(null);
                        jTextFieldDado.setText(null);
                    }
                }
                if (jCheckBox4.isSelected()) {
                    String Color = jCheckBox4.getText();

                    if (Login.metodos.crearFunciones(Color, Adelantar, Retrasar, LanzarDado) == true) {
                        JOptionPane.showMessageDialog(null, "Funcion creada");
                        Login.menuAdmin.setVisible(true);
                        this.dispose();
                        jTextFieldAdelantar.setText(null);
                        jTextFieldRetrasar.setText(null);
                        jTextFieldDado.setText(null);
                    }
                }
                if (jCheckBox5.isSelected()) {
                    String Color = jCheckBox5.getText();

                    if (Login.metodos.crearFunciones(Color, Adelantar, Retrasar, LanzarDado) == true) {
                        JOptionPane.showMessageDialog(null, "Funcion creada");
                        Login.menuAdmin.setVisible(true);
                        this.dispose();
                        jTextFieldAdelantar.setText(null);
                        jTextFieldRetrasar.setText(null);
                        jTextFieldDado.setText(null);
                    }
                }
            } else {
                if (Adelantar == 0 && Retrasar != 0 && LanzarDado == 0) {
                    if (jCheckBox1.isSelected()) {
                        String Color = jCheckBox1.getText();
                        if (Login.metodos.crearFunciones(Color, Adelantar, Retrasar, LanzarDado) == true) {
                            JOptionPane.showMessageDialog(null, "Funcion creada");
                            Login.menuAdmin.setVisible(true);
                            this.dispose();
                            jTextFieldAdelantar.setText(null);
                            jTextFieldRetrasar.setText(null);
                            jTextFieldDado.setText(null);
                        }
                    }
                    if (jCheckBox2.isSelected()) {
                        String Color = jCheckBox2.getText();

                        if (Login.metodos.crearFunciones(Color, Adelantar, Retrasar, LanzarDado) == true) {
                            JOptionPane.showMessageDialog(null, "Funcion creada");
                            Login.menuAdmin.setVisible(true);
                            this.dispose();
                            jTextFieldAdelantar.setText(null);
                            jTextFieldRetrasar.setText(null);
                            jTextFieldDado.setText(null);
                        }
                    }
                    if (jCheckBox3.isSelected()) {
                        String Color = jCheckBox3.getText();

                        if (Login.metodos.crearFunciones(Color, Adelantar, Retrasar, LanzarDado) == true) {
                            JOptionPane.showMessageDialog(null, "Funcion creada");
                            Login.menuAdmin.setVisible(true);
                            this.dispose();
                            jTextFieldAdelantar.setText(null);
                            jTextFieldRetrasar.setText(null);
                            jTextFieldDado.setText(null);
                        }
                    }
                    if (jCheckBox4.isSelected()) {
                        String Color = jCheckBox4.getText();

                        if (Login.metodos.crearFunciones(Color, Adelantar, Retrasar, LanzarDado) == true) {
                            JOptionPane.showMessageDialog(null, "Funcion creada");
                            Login.menuAdmin.setVisible(true);
                            this.dispose();
                            jTextFieldAdelantar.setText(null);
                            jTextFieldRetrasar.setText(null);
                            jTextFieldDado.setText(null);
                        }
                    }
                    if (jCheckBox5.isSelected()) {
                        String Color = jCheckBox5.getText();

                        if (Login.metodos.crearFunciones(Color, Adelantar, Retrasar, LanzarDado) == true) {
                            JOptionPane.showMessageDialog(null, "Funcion creada");
                            Login.menuAdmin.setVisible(true);
                            this.dispose();
                            jTextFieldAdelantar.setText(null);
                            jTextFieldRetrasar.setText(null);
                            jTextFieldDado.setText(null);
                        }
                    }
                } else {
                    if (Adelantar == 0 && Retrasar == 0 && LanzarDado == 1) {
                        if (jCheckBox1.isSelected()) {
                            String Color = jCheckBox1.getText();
                            if (Login.metodos.crearFunciones(Color, Adelantar, Retrasar, LanzarDado) == true) {
                                JOptionPane.showMessageDialog(null, "Funcion creada");
                                Login.menuAdmin.setVisible(true);
                                this.dispose();
                                jTextFieldAdelantar.setText(null);
                                jTextFieldRetrasar.setText(null);
                                jTextFieldDado.setText(null);
                            }
                        }
                        if (jCheckBox2.isSelected()) {
                            String Color = jCheckBox2.getText();

                            if (Login.metodos.crearFunciones(Color, Adelantar, Retrasar, LanzarDado) == true) {
                                JOptionPane.showMessageDialog(null, "Funcion creada");
                                Login.menuAdmin.setVisible(true);
                                this.dispose();
                                jTextFieldAdelantar.setText(null);
                                jTextFieldRetrasar.setText(null);
                                jTextFieldDado.setText(null);
                            }
                        }
                        if (jCheckBox3.isSelected()) {
                            String Color = jCheckBox3.getText();

                            if (Login.metodos.crearFunciones(Color, Adelantar, Retrasar, LanzarDado) == true) {
                                JOptionPane.showMessageDialog(null, "Funcion creada");
                                Login.menuAdmin.setVisible(true);
                                this.dispose();
                                jTextFieldAdelantar.setText(null);
                                jTextFieldRetrasar.setText(null);
                                jTextFieldDado.setText(null);
                            }
                        }
                        if (jCheckBox4.isSelected()) {
                            String Color = jCheckBox4.getText();

                            if (Login.metodos.crearFunciones(Color, Adelantar, Retrasar, LanzarDado) == true) {
                                JOptionPane.showMessageDialog(null, "Funcion creada");
                                Login.menuAdmin.setVisible(true);
                                this.dispose();
                                jTextFieldAdelantar.setText(null);
                                jTextFieldRetrasar.setText(null);
                                jTextFieldDado.setText(null);
                            }
                        }
                        if (jCheckBox5.isSelected()) {
                            String Color = jCheckBox5.getText();

                            if (Login.metodos.crearFunciones(Color, Adelantar, Retrasar, LanzarDado) == true) {
                                JOptionPane.showMessageDialog(null, "Funcion creada");
                                Login.menuAdmin.setVisible(true);
                                this.dispose();
                                jTextFieldAdelantar.setText(null);
                                jTextFieldRetrasar.setText(null);
                                jTextFieldDado.setText(null);
                            }
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Solo puede usar una opcion");
                        return;
                    }
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextFieldAdelantarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAdelantarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAdelantarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFunciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFunciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFunciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFunciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFunciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public static final javax.swing.JTextField jTextFieldAdelantar = new javax.swing.JTextField();
    public static final javax.swing.JTextField jTextFieldDado = new javax.swing.JTextField();
    public static final javax.swing.JTextField jTextFieldRetrasar = new javax.swing.JTextField();
    // End of variables declaration//GEN-END:variables
}
