/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Dado extends javax.swing.JFrame {

    //Variable global para almacenar el numero del dado
    public static int NumeroDado;

    //Variable para saber si el dado ya fue usado
    boolean Activo;
    String path1 = "/Imagenes/Dado.gif";
    URL url1 = this.getClass().getResource(path1);
    public ImageIcon icon = new ImageIcon(url1);

    //
    public boolean RefrescarDado = true;

    /**
     * Creates new form Dado
     */
    public Dado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelDado = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelDado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Dado.gif"))); // NOI18N

        jButton1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton1.setText("Parar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton2.setText("volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Activar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 124, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelDado)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(46, 46, 46))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelDado)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addGap(56, 56, 56)))
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (RefrescarDado != false) {
            int Numero = (int) (Math.random() * 7);
            if (Numero == 1 || Numero == 0) {
                NumeroDado = 1;
                String path1 = "/Imagenes/Numero1.png";
                URL url1 = this.getClass().getResource(path1);
                ImageIcon icon1 = new ImageIcon(url1);
                jLabelDado.setIcon(icon1);
            }
            if (Numero == 1) {
                NumeroDado = 1;
                String path1 = "/Imagenes/Numero1.png";
                URL url1 = this.getClass().getResource(path1);
                ImageIcon icon1 = new ImageIcon(url1);
                jLabelDado.setIcon(icon1);
            }
            if (Numero == 2) {
                NumeroDado = 2;
                String path1 = "/Imagenes/Numero2.png";
                URL url1 = this.getClass().getResource(path1);
                ImageIcon icon1 = new ImageIcon(url1);
                jLabelDado.setIcon(icon1);
            }
            if (Numero == 3) {
                NumeroDado = 3;
                String path1 = "/Imagenes/Numero3.png";
                URL url1 = this.getClass().getResource(path1);
                ImageIcon icon1 = new ImageIcon(url1);
                jLabelDado.setIcon(icon1);
            }
            if (Numero == 4) {
                NumeroDado = 4;
                String path1 = "/Imagenes/Numero4.png";
                URL url1 = this.getClass().getResource(path1);
                ImageIcon icon1 = new ImageIcon(url1);
                jLabelDado.setIcon(icon1);
            }
            if (Numero == 5) {
                NumeroDado = 5;
                String path1 = "/Imagenes/Numero5.png";
                URL url1 = this.getClass().getResource(path1);
                ImageIcon icon1 = new ImageIcon(url1);
                jLabelDado.setIcon(icon1);
            }
            if (Numero == 6) {
                NumeroDado = 6;
                String path1 = "/Imagenes/Numero6.png";
                URL url1 = this.getClass().getResource(path1);
                ImageIcon icon1 = new ImageIcon(url1);
                jLabelDado.setIcon(icon1);
            }
            Login.metodos.dado();
            RefrescarDado = false;
        } else {
            JOptionPane.showMessageDialog(null, "Activa el dado");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Cerrar la ventana y restablecer el jlabel
        this.dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (RefrescarDado == false) {
            jLabelDado.setIcon(icon);
            RefrescarDado = true;
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabelDado;
    // End of variables declaration//GEN-END:variables
}
