package Interfaz;

import Clases.Metodos;
import Clases.*;
import static Interfaz.MenuAdmin.AdminInfo;
import static Interfaz.MenuUsuarios.UsuarioInfo;
import com.sun.org.apache.bcel.internal.generic.AALOAD;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Usuario
 */
public class Login extends javax.swing.JFrame {

    //Intancia Interfaces
    public static Login login = new Login();
    public static Registro registro = new Registro();
    public static MenuUsuarios menuUsuarios = new MenuUsuarios();
    public static MenuAdmin menuAdmin = new MenuAdmin();
    public static AdminFunciones adminFunciones = new AdminFunciones();
    public static UsuarioAjustes usuarioAjustes = new UsuarioAjustes();
    public static UsuarioMapa usuarioMapa = new UsuarioMapa();
    public static MapaNuevo mapaNuevo = new MapaNuevo();
    public static AsignarFunciones asignarFunciones = new AsignarFunciones();
    public static AdminUsuarios adminUsuarios = new AdminUsuarios();
    public static AdminMapas adminMapas = new AdminMapas();
    public static AgregarFichas agregarFichas = new AgregarFichas();
    public static CargarMapa cargarMapa = new CargarMapa();
    public static SeleccionFichas seleccionFichas = new SeleccionFichas();
    public static Dado dado = new Dado();

    //Intancia Metodos
    public static Metodos metodos = new Metodos();

    //Respaldo de datos
    public static Usuarios RespaldoUsuario;
    public static Admin RespaldoAdmin;

    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Usuario:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jButton1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton1.setText("Iniciar Sesion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, -1, -1));

        jButton2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton2.setText("Registrarse");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 132, -1));

        jTextField1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 151, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Contraseña:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jPasswordField1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 151, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MR.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/720px-Monopoly_game_logo.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Extrae la informacion de los cuadros de texto y luego la verifica
        if (jTextField1.getText().isEmpty() | jPasswordField1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "No deje espacios sin rellenar");
        } else {
            String NombreUsuario = jTextField1.getText();
            String Contraseña = jPasswordField1.getText();

            //Admin
            login.metodos.RegistrarAdministrador("a", "a", 22, "Admin", "admin", "Admin");
                
            // El metodo "InicioSesion" retorna un objeto tipo usuario, y la vartiable usuario almacena la informacion.
            Usuarios usuarios = login.metodos.InicioSesion(NombreUsuario, Contraseña);

            // El metodo "InicioSesionAdmin" retorna un objeto tipo admin, y la vartiable admin almacena la informacion.
            Admin admin = login.metodos.InicioSesionAdmin(NombreUsuario, Contraseña);

            if (usuarios != null) {
                RespaldoUsuario = usuarios;

                if (RespaldoUsuario.getTipoUsuario().equals("Corriente")) {
                    login.menuUsuarios.setVisible(true);
                    this.dispose();
                    UsuarioInfo.setText(login.RespaldoUsuario.getNombreUsuario());
                    jTextField1.setText(null);
                    jPasswordField1.setText(null);

                } else {

                    JOptionPane.showMessageDialog(null, "Usuario no exite");
                    jTextField1.setText(null);
                    jPasswordField1.setText(null);

                }

            } else {
                if (admin != null) {
                    RespaldoAdmin = admin;
                    if (RespaldoAdmin.getTipoUsuario().equals("Admin")) {
                        login.menuAdmin.setVisible(true);
                        this.dispose();
                        AdminInfo.setText(login.RespaldoAdmin.getNombreUsuario());
                        jTextField1.setText(null);
                        jPasswordField1.setText(null);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Usuario no exite");
                    jTextField1.setText(null);
                    jPasswordField1.setText(null);
                }

            }
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Retorna a la ventana (Login)
        login.registro.setVisible(true);
        this.dispose();

        //Limpia los cuadros de texto
        jTextField1.setText(null);
        jPasswordField1.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
